<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007171829 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, username VARCHAR(30) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE TABLE watched_movie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT NOT NULL, title VARCHAR(255) NOT NULL, poster_path VARCHAR(255) DEFAULT NULL, release_date VARCHAR(10) DEFAULT NULL, watched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rating SMALLINT DEFAULT NULL, review TEXT DEFAULT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_user_watched_at ON watched_movie (user_id, watched_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_movie ON watched_movie (user_id, tmdb_id)');
        $this->addSql('CREATE INDEX IDX_29C2D8FEA76ED395 ON watched_movie (user_id)');
        $this->addSql('ALTER TABLE watched_movie ADD CONSTRAINT FK_29C2D8FEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE watched_movie DROP CONSTRAINT FK_29C2D8FEA76ED395');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE watched_movie');
    }
}
