<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds folders: folder (owned by a user), movie (one shared row per TMDB movie) and
 * folder_movie, the join table behind the Folder <-> Movie ManyToMany.
 * Only new tables, so unlike Version20261008182333 no existing rows need filling in.
 */
final class Version20261008184801 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add folders: folder, movie and the folder_movie join table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(50) NOT NULL, is_public BOOLEAN NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_owner_folder_name ON folder (owner_id, name)');
        $this->addSql('CREATE INDEX IDX_ECA209CD7E3C61F9 ON folder (owner_id)');
        $this->addSql('CREATE TABLE folder_movie (folder_id INT NOT NULL, movie_id INT NOT NULL, PRIMARY KEY (folder_id, movie_id))');
        $this->addSql('CREATE INDEX IDX_709A89A2162CB942 ON folder_movie (folder_id)');
        $this->addSql('CREATE INDEX IDX_709A89A28F93B6FC ON folder_movie (movie_id)');
        $this->addSql('CREATE TABLE movie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT NOT NULL, title VARCHAR(255) NOT NULL, poster_path VARCHAR(255) DEFAULT NULL, release_date VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D5EF26F55BCC5E5 ON movie (tmdb_id)');
        $this->addSql('ALTER TABLE folder ADD CONSTRAINT FK_ECA209CD7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folder_movie ADD CONSTRAINT FK_709A89A2162CB942 FOREIGN KEY (folder_id) REFERENCES folder (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE folder_movie ADD CONSTRAINT FK_709A89A28F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE folder DROP CONSTRAINT FK_ECA209CD7E3C61F9');
        $this->addSql('ALTER TABLE folder_movie DROP CONSTRAINT FK_709A89A2162CB942');
        $this->addSql('ALTER TABLE folder_movie DROP CONSTRAINT FK_709A89A28F93B6FC');
        $this->addSql('DROP TABLE folder');
        $this->addSql('DROP TABLE folder_movie');
        $this->addSql('DROP TABLE movie');
    }
}
