<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds the want-to-watch list: a status column on watched_movie, plus added_at.
 * Generated by make:migration, then edited so the rows already in the table survive:
 * the generated "ADD ... NOT NULL" fails on a non-empty table, because existing rows get no value.
 */
final class Version20261008182333 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add status and added_at to watched_movie for the want-to-watch list';
    }

    public function up(Schema $schema): void
    {
        // Every existing row is a watched movie. The default fills them in, then goes away,
        // because the mapping has none: new rows always get a status from the code.
        $this->addSql("ALTER TABLE watched_movie ADD status VARCHAR(10) DEFAULT 'watched' NOT NULL");
        $this->addSql('ALTER TABLE watched_movie ALTER status DROP DEFAULT');

        // Add the column as nullable, copy the watch date into it, and only then require a value
        $this->addSql('ALTER TABLE watched_movie ADD added_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('UPDATE watched_movie SET added_at = watched_at');
        $this->addSql('ALTER TABLE watched_movie ALTER added_at SET NOT NULL');

        // Wanted movies have not been watched yet
        $this->addSql('ALTER TABLE watched_movie ALTER watched_at DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // Wanted movies have no watched_at and cannot exist in the old schema, so they are lost
        $this->addSql("DELETE FROM watched_movie WHERE status = 'want'");
        $this->addSql('ALTER TABLE watched_movie DROP status');
        $this->addSql('ALTER TABLE watched_movie DROP added_at');
        $this->addSql('ALTER TABLE watched_movie ALTER watched_at SET NOT NULL');
    }
}
